#!/usr/bin/env python
import argparse
import json
import os
import subprocess
import sys

from ast import literal_eval
from datetime import datetime, timedelta

from dbt_helpers import (
    _model_path_check, _run_models_user_input, rebuild,
    _drop_existing_views, COMPLETION_PING,
    _remove_orphaned_containers
)


DBT_HOME = '/usr/local/data-vault'
ENV = os.environ.copy()

parser = argparse.ArgumentParser(description='Run DBT with supplied args.')
parser.add_argument('--profiles-dir', default=f'{DBT_HOME}/profiles', help='Will supply the specified profile.')
parser.add_argument('--project-dir', default='wealthsimple', help='Will supply the specified project.')
parser.add_argument('--vars', default=str({"ds": f"{(datetime.now() - timedelta(1)).strftime('%Y-%m-%d')}"}), help='Will supply the specified vars.')
parser.add_argument('--select', nargs='+', required=False, help='Your model or path to build.')
parser.add_argument('--rebuild', action=argparse.BooleanOptionalAction, help='Runs the rebuild command prior to your DBT command.')
parser.add_argument('--drop-existing', action=argparse.BooleanOptionalAction, default=False, help='Drops any existing views.')
parser.add_argument('--exclude', nargs='+', required=False, help='Models to exclude')

try:
    proc = subprocess.run(f"ssh -M -S ~/data-vault-ctrl-socket-{ENV['JUMPBOX_HOST_PROD']} -fnNT -L {ENV['LOCAL_FORWARD_PANTHEON']} {ENV['SSH_USER']}@{ENV['JUMPBOX_HOST_PROD']}", shell=True, capture_output=True, text=True)
    if proc.returncode != 0:
        raise Exception('Unable to establish tunnel. Please connect to VPN.')

    args, unargs = parser.parse_known_args()

    parsed_args = []
    select_stmt = ' '.join(args.select) if args.select else ''
    if args.select:
        parsed_args.extend(['--select', select_stmt])

    if args.profiles_dir:
        parsed_args.extend(['--profiles-dir', args.profiles_dir])

    if args.project_dir:
        project_dir = f'{DBT_HOME}/projects/{args.project_dir}'
        dbt_modules_dir = f'{os.getcwd()}/projects/{args.project_dir}/dbt_modules'

        if not os.path.isdir(dbt_modules_dir) or len(os.listdir(dbt_modules_dir)) == 0:
            print(f'Checking for missing dependencies @ {dbt_modules_dir}')
            print('Missing dependencies. Installing...')
            subprocess.run(f'docker compose run dbt deps --project-dir={project_dir} --profiles-dir={args.profiles_dir}', shell=True)

        parsed_args.extend(['--project-dir', project_dir])

    exclude_stmt = ' '.join(args.exclude) if args.exclude else ''
    if args.exclude:
        parsed_args.extend(['--exclude', exclude_stmt])
        exclude_ls_stmt = f'--exclude {exclude_stmt}'
    else:
        exclude_ls_stmt = ''

    # handle vars - we extend with ds if not supplied
    dbt_vars_dict = literal_eval(args.vars)
    if 'ds' not in dbt_vars_dict.keys():
        dbt_vars_dict['ds'] = (datetime.now() - timedelta(1)).strftime('%Y-%m-%d')
    dbt_vars = '"' + f"{dbt_vars_dict}" + '"'
    parsed_args.extend(['--vars', dbt_vars])

    unargs.extend(parsed_args)

    if args.rebuild:
        target_path = f'{os.getcwd()}/projects/{args.project_dir}/target'
        rebuild(args.select, project_dir, args.profiles_dir, target_path, dbt_vars)
        print('\nRebuild complete. Running DBT command...\n')

    if args.drop_existing:
        tables = select_stmt.split(' ')
        _drop_existing_views(args.select, profiles_dir=args.profiles_dir, project_dir=project_dir, dbt_vars=dbt_vars)

    if not ('ls' in unargs or 'list' in unargs or 'deps' in unargs):
        if _model_path_check(select_stmt):
            models_to_run = subprocess.run(f'docker compose run --service-ports dbt --quiet ls --select {select_stmt} --project-dir {project_dir} --profiles {args.profiles_dir} --resource-type model {exclude_ls_stmt}', shell=True, capture_output=True, text=True).stdout.split('\n')
            print(f'Your command runs the following models: \n{chr(10).join(models_to_run)}')
            _run_models_user_input(models_to_run, 10)
    # Run the DBT cmd
    dbt_proc = subprocess.run(f'docker compose run --service-ports dbt {" ".join(unargs)} {COMPLETION_PING}', shell=True)
    _remove_orphaned_containers()
except Exception as e:
    sys.exit(e)

if proc.returncode == 0:
    subprocess.run(f"ssh -S ~/data-vault-ctrl-socket-{ENV['JUMPBOX_HOST_PROD']} -O exit {ENV['SSH_USER']}@{ENV['JUMPBOX_HOST_PROD']}", shell=True, capture_output=True, text=True)

sys.exit(dbt_proc.returncode)
