#!/usr/bin/env python3
"""
Mock GitHub validation script to test PR JSON generation.
Validates that auto-publish path generates well-formed PR JSON.
"""

import json
import re
from typing import Dict, Any, List

def validate_pr_json_structure(pr_json: Dict[str, Any]) -> List[str]:
    """Validate the structure of PR JSON from getCreatePRPrompt."""
    errors = []
    
    # Required top-level fields
    required_fields = [
        "pr_metadata",
        "pr_description", 
        "pr_checklist",
        "release_notes",
        "deployment_plan",
        "formatted_pr_content"
    ]
    
    for field in required_fields:
        if field not in pr_json:
            errors.append(f"Missing required field: {field}")
    
    # Validate pr_metadata structure
    if "pr_metadata" in pr_json:
        metadata = pr_json["pr_metadata"]
        required_metadata = ["title", "branch_name", "base_branch", "labels", "reviewers", "priority"]
        
        for field in required_metadata:
            if field not in metadata:
                errors.append(f"Missing pr_metadata field: {field}")
        
        # Validate default title for auto-generated PRs
        if "title" in metadata:
            expected_title = "🔄 Refactor / Cleanup – auto-generated by MCP"
            if metadata["title"] == expected_title:
                print(f"✅ Default PR title correct: {metadata['title']}")
            else:
                print(f"📝 Custom PR title: {metadata['title']}")
    
    # Validate pr_description structure
    if "pr_description" in pr_json:
        description = pr_json["pr_description"]
        required_desc = ["summary", "motivation", "changes", "technical_details"]
        
        for field in required_desc:
            if field not in description:
                errors.append(f"Missing pr_description field: {field}")
    
    # Validate formatted_pr_content is markdown
    if "formatted_pr_content" in pr_json:
        content = pr_json["formatted_pr_content"]
        if not isinstance(content, str):
            errors.append("formatted_pr_content must be a string")
        elif len(content) < 100:
            errors.append("formatted_pr_content seems too short for a proper PR description")
        elif not content.startswith("#"):
            errors.append("formatted_pr_content should start with a markdown header")
    
    return errors

def validate_auto_publish_chain() -> bool:
    """Validate the auto-publish chain integration."""
    print("🔗 Validating auto-publish chain integration...")
    
    # Simulate PR JSON from auto-generated flow
    mock_pr_json = {
        "pr_metadata": {
            "title": "🔄 Refactor / Cleanup – auto-generated by MCP",
            "branch_name": "auto/reconciliation-cleanup",
            "base_branch": "main",
            "labels": ["auto-generated", "reconciliation", "cleanup"],
            "reviewers": ["@data-team-lead"],
            "priority": "medium",
            "estimated_review_time": "15 minutes"
        },
        "pr_description": {
            "summary": "Automated cleanup and reconciliation for models: stg_orders, fct_revenue",
            "motivation": "Auto-generated PR from successful dbt build and Preset reconciliation",
            "changes": [
                {
                    "category": "Reconciliation",
                    "description": "Validated schema and data consistency across environments"
                }
            ],
            "technical_details": "All models passed reconciliation with 0 schema issues and acceptable data variance",
            "testing_approach": "Automated testing via dbt build and Preset reconciliation",
            "test_results": "All tests passing, reconciliation successful",
            "performance_impact": "No performance impact, cleanup only",
            "dependencies": "No blocking dependencies",
            "migration_notes": "No migration required",
            "documentation_updates": "Documentation automatically updated",
            "screenshots": "Reconciliation table included in PR description"
        },
        "pr_checklist": [
            {
                "item": "dbt build completed successfully",
                "checked": True,
                "notes": "All models built without errors"
            },
            {
                "item": "Reconciliation passed",
                "checked": True,
                "notes": "All models show green status"
            },
            {
                "item": "Schema validation completed",
                "checked": True,
                "notes": "No schema mismatches detected"
            }
        ],
        "release_notes": {
            "user_facing_changes": "No user-facing changes, internal cleanup only",
            "internal_changes": "Validated data consistency and schema alignment",
            "breaking_changes": "None",
            "required_actions": "None"
        },
        "deployment_plan": {
            "deployment_steps": [
                "Merge PR after approval",
                "No additional deployment steps required",
                "Monitor reconciliation metrics"
            ],
            "rollback_plan": "No rollback needed for reconciliation validation",
            "verification_steps": [
                "Verify reconciliation metrics remain green",
                "Confirm no regressions in downstream models"
            ]
        },
        "formatted_pr_content": "# Refactor / Cleanup – auto-generated by MCP\n\n## Summary\nAutomated cleanup and reconciliation for models: stg_orders, fct_revenue\n\n## Reconciliation Results\n✅ All models passed validation\n\n## Checklist\n- [x] dbt build completed successfully\n- [x] Reconciliation passed\n- [x] Schema validation completed"
    }
    
    # Validate the JSON structure
    errors = validate_pr_json_structure(mock_pr_json)
    
    if errors:
        print("❌ PR JSON validation failed:")
        for error in errors:
            print(f"   - {error}")
        return False
    else:
        print("✅ PR JSON structure is well-formed")
    
    # Validate specific auto-publish requirements
    print("\n🔍 Validating auto-publish specific requirements:")
    
    # Check title
    title = mock_pr_json["pr_metadata"]["title"]
    expected_title = "🔄 Refactor / Cleanup – auto-generated by MCP"
    if title == expected_title:
        print(f"✅ Default title correct: {title}")
    else:
        print(f"❌ Title mismatch. Expected: {expected_title}, Got: {title}")
        return False
    
    # Check auto-generated label
    labels = mock_pr_json["pr_metadata"]["labels"]
    if "auto-generated" in labels:
        print("✅ Auto-generated label present")
    else:
        print("❌ Missing 'auto-generated' label")
        return False
    
    # Check reconciliation context
    summary = mock_pr_json["pr_description"]["summary"]
    if "reconciliation" in summary.lower():
        print("✅ Reconciliation context included in summary")
    else:
        print("❌ Missing reconciliation context")
        return False
    
    print("\n🎉 Auto-publish PR JSON validation successful!")
    return True

def simulate_github_api_response():
    """Simulate GitHub API response for PR creation."""
    print("\n🐙 Simulating GitHub API response:")
    
    mock_response = {
        "id": 123456789,
        "number": 123,
        "title": "🔄 Refactor / Cleanup – auto-generated by MCP",
        "state": "open",
        "html_url": "https://github.com/example/repo/pull/123",
        "user": {
            "login": "mcp-bot"
        },
        "created_at": "2025-01-16T10:30:00Z",
        "updated_at": "2025-01-16T10:30:00Z",
        "mergeable": True,
        "mergeable_state": "clean",
        "merged": False,
        "draft": False,
        "labels": [
            {"name": "auto-generated"},
            {"name": "reconciliation"},
            {"name": "cleanup"}
        ]
    }
    
    print(f"✅ PR created: {mock_response['html_url']}")
    print(f"✅ PR number: #{mock_response['number']}")
    print(f"✅ State: {mock_response['state']}")
    print(f"✅ Mergeable: {mock_response['mergeable']}")
    
    return mock_response

def validate_merge_guard_input():
    """Validate that PR data can be properly passed to getMergeGuardPrompt."""
    print("\n🛡️ Validating merge guard integration:")
    
    pr_response = simulate_github_api_response()
    
    # Simulate merge guard input
    merge_guard_input = {
        "pr_id": f"PR-{pr_response['number']}",
        "pr_title": pr_response["title"],
        "auto_generated": True,
        "reconciliation_passed": True,
        "pr_url": pr_response["html_url"],
        "mergeable": pr_response["mergeable"],
        "state": pr_response["state"]
    }
    
    print(f"✅ Merge guard input prepared:")
    for key, value in merge_guard_input.items():
        print(f"   - {key}: {value}")
    
    return True

if __name__ == "__main__":
    print("🧪 Mock GitHub PR JSON Validation")
    print("=" * 50)
    
    success1 = validate_auto_publish_chain()
    success2 = validate_merge_guard_input()
    
    if success1 and success2:
        print("\n🎊 All GitHub integration validations passed!")
        print("💬 Auto-publish workflow:")
        print("   1. getReconcilePrompt → ✅ Success")
        print("   2. getCreatePRPrompt → 📝 Well-formed JSON")
        print("   3. GitHub API → 🐙 PR created") 
        print("   4. getMergeGuardPrompt → 🛡️ Ready for validation")
        exit(0)
    else:
        print("\n❌ GitHub integration validation failed!")
        exit(1) 